base_url = "13ros27.github.io"
title = "anemone"
compile_sass = true
minify_html = true
build_search_index = false

theme = "anemone"

[markdown]
highlight_code = true

[link_checker]
internal_level = "warn"

[extra]
favicon = "favicon.ico"
image = ""
default_theme = "night"

header_nav = [
  { url = "/blog", name_en = "/blog/" }
]
