base_url = "https://13ros27.github.io"
title = "Blog Posts"
compile_sass = true
minify_html = true
build_search_index = false

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

theme = "anemone"

[markdown]
highlight_code = true

[link_checker]
internal_level = "warn"

[extra]
favicon = "favicon.ico"
image = ""
default_theme = "night"

header_nav = [
  { url = "/atom.xml", "name_en" = "/atom/" },
  { url = "/rss.xml", name_en = "/rss/" },
  { url = "/blog", name_en = "/blog/" }
]
